- name: Hello World Sample
  hosts: 192.168.0.12
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Create Report Check Parameter
      template:
        src: index.html.j2
        dest: /tmp/192.168.0.12.html
    - name: Fetch Report Check Parameter
      fetch:
        src: /tmp/192.168.0.12.html
        dest: /tmp/192.168.0.12.html
        flat: yes

- name: fetch to 192.168.0.11
  hosts: 192.168.0.11
  tasks:
    - name: Fetch Report Check Parameter
      copy:
        src: /tmp/192.168.0.12.html
        dest: /var/www/html/
