- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Create a DNS A record
      infoblox.nios_modules.nios_a_record:
        name: "host.example.com"
        ipv4addr: "192.168.1.10"
        state: "present"

