- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"


    - name: Create host record in Infoblox
      ansible.builtin.infoblox_nios_host_record:
        name: "host.example.com"
        ipv4addr: "192.168.1.10"
        state: "present"
        view: "default"
        provider:
          host: "infoblox-server.example.com"
          username: "your-username"
          password: "your-password"
          ssl_verify: False
        ttl: 3600
        extattrs: null
        comment: "Created via Ansible"