- name: Hello World Sample
  hosts: 192.168.0.11
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Create Report Check Parameter
      template:
        src: index.html.j2
        dest: /tmp/index.html

- name: fetch to 192.168.0.12
  hosts: 192.168.0.12
  tasks:
    - name: Fetch Report Check Parameter
      copy:
        src: /tmp/index.html
        dest: /var/www/html/
