- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Create Report Check Parameter
      template:
        src: index.html.j2
        dest: /tmp/index.html

